name: Python Ukol 1 Tests

on:
  push:
    paths:
      - 'Ukol_1/**'
      - '.github/workflows/testUkol1.yml'
  pull_request:
    paths:
      - 'Ukol_1/**'
      - '.github/workflows/testUkol1.yml'

jobs:
  python_test:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' || 
      github.event.repository.fork == true || 
      github.ref != 'refs/heads/master'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run Python test for Ukol 1
      run: |
        cd Ukol_1 && python -m unittest test.py
